In [1]:
import pandas as pd
# Load data into a DataFrame
data = pd.read_excel("cd.xlsx")



data

,S.NO,Date,Company Name,Contact Person No,Delivery Order No,Tranporter Details,Tranport C P,Loading Point,Unloading Point,Coal.Weight,Truck No.,Freight Fair,Freight Chrgs
0,1.0,22/06/2022,Sendoz Impex Limited,Prakash,DO20221056,Singh Roadlines,Deepak/Prashant,Suliyari,Nepal,39.79,UP72AT7101,3200.0,127328.0
1,2.0,22/06/2022,Sendoz Impex Limited,Prakash,DO20221056,Singh Roadlines,Deepak/Prashant,Suliyari,Nepal,28.92,UP72AT6700,3200.0,92544.0
2,3.0,22/06/2022,Sendoz Impex Limited,Prakash,DO20221056,Singh Roadlines,Deepak/Prashant,Suliyari,Nepal,29.43,UP72AT2568,3200.0,94176.0
3,4.0,22/06/2022,Sendoz Impex Limited,Prakash,DO20221056,Singh Roadlines,Deepak/Prashant,Suliyari,Nepal,28.98,UP72AT2886,3200.0,92736.0
4,5.0,23/06/2022,Sendoz Impex Limited,Prakash,DO20221056,Singh Roadlines,Deepak/Prashant,Suliyari,Nepal,30.17,UP72AT3324,3200.0,96544.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,73.0,19/08/2022,Sendoz Impex Limited,Prakash,DO20221056,Balaji Traders,Deepak/Prashant,Suliyari,Nepal,28.59,UP72AT2172,3200.0,91488.0
73,74.0,19/08/2022,Sendoz Impex Limited,Prakash,DO20221056,Balaji Traders,Deepak/Prashant,Suliyari,Nepal,28.95,CG04LE1272,3200.0,92640.0
74,75.0,19/08/2022,Sendoz Impex Limited,Prakash,DO20221056,Balaji Traders,Deepak/Prashant,Suliyari,Nepal,29.47,CG04ME3060,3200.0,94304.0
75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8000896.0

In [2]:
data.drop(data.tail(2).index,inplace=True)

In [3]:
data.isnull().sum()

S.NO                  0
Date                  0
Company Name          0
Contact Person No     0
Delivery Order No     0
Tranporter Details    0
Tranport C P          0
Loading Point         0
Unloading Point       0
Coal.Weight           1
Truck No.             0
Freight Fair          0
Freight Chrgs         0
dtype: int64

In [4]:
data['Coal.Weight']=data['Coal.Weight'].fillna(data['Coal.Weight'].mean())

In [5]:
# Calculate total cost
data['Total Cost'] = data['Freight Chrgs']

In [6]:
data.head()

,S.NO,Date,Company Name,Contact Person No,Delivery Order No,Tranporter Details,Tranport C P,Loading Point,Unloading Point,Coal.Weight,Truck No.,Freight Fair,Freight Chrgs,Total Cost
0,1.0,22/06/2022,Sendoz Impex Limited,Prakash,DO20221056,Singh Roadlines,Deepak/Prashant,Suliyari,Nepal,39.79,UP72AT7101,3200.0,127328.0,127328.0
1,2.0,22/06/2022,Sendoz Impex Limited,Prakash,DO20221056,Singh Roadlines,Deepak/Prashant,Suliyari,Nepal,28.92,UP72AT6700,3200.0,92544.0,92544.0
2,3.0,22/06/2022,Sendoz Impex Limited,Prakash,DO20221056,Singh Roadlines,Deepak/Prashant,Suliyari,Nepal,29.43,UP72AT2568,3200.0,94176.0,94176.0
3,4.0,22/06/2022,Sendoz Impex Limited,Prakash,DO20221056,Singh Roadlines,Deepak/Prashant,Suliyari,Nepal,28.98,UP72AT2886,3200.0,92736.0,92736.0
4,5.0,23/06/2022,Sendoz Impex Limited,Prakash,DO20221056,Singh Roadlines,Deepak/Prashant,Suliyari,Nepal,30.17,UP72AT3324,3200.0,96544.0,96544.0

In [7]:
# Calculate total revenue
data['Total Revenue'] = data['Coal.Weight'] * data['Freight Fair']

In [8]:
data

,S.NO,Date,Company Name,Contact Person No,Delivery Order No,Tranporter Details,Tranport C P,Loading Point,Unloading Point,Coal.Weight,Truck No.,Freight Fair,Freight Chrgs,Total Cost,Total Revenue
0,1.0,22/06/2022,Sendoz Impex Limited,Prakash,DO20221056,Singh Roadlines,Deepak/Prashant,Suliyari,Nepal,39.79,UP72AT7101,3200.0,127328.0,127328.0,127328.0
1,2.0,22/06/2022,Sendoz Impex Limited,Prakash,DO20221056,Singh Roadlines,Deepak/Prashant,Suliyari,Nepal,28.92,UP72AT6700,3200.0,92544.0,92544.0,92544.0
2,3.0,22/06/2022,Sendoz Impex Limited,Prakash,DO20221056,Singh Roadlines,Deepak/Prashant,Suliyari,Nepal,29.43,UP72AT2568,3200.0,94176.0,94176.0,94176.0
3,4.0,22/06/2022,Sendoz Impex Limited,Prakash,DO20221056,Singh Roadlines,Deepak/Prashant,Suliyari,Nepal,28.98,UP72AT2886,3200.0,92736.0,92736.0,92736.0
4,5.0,23/06/2022,Sendoz Impex Limited,Prakash,DO20221056,Singh Roadlines,Deepak/Prashant,Suliyari,Nepal,30.17,UP72AT3324,3200.0,96544.0,96544.0,96544.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,71.0,19/08/2022,Sendoz Impex Limited,Prakash,DO20221056,Balaji Traders,Deepak/Prashant,Suliyari,Nepal,29.69,CG15DG7596,3200.0,95008.0,95008.0,95008.0
71,72.0,19/08/2022,Sendoz Impex Limited,Prakash,DO20221056,Balaji Traders,Deepak/Prashant,Suliyari,Nepal,29.16,CG29AB0150,3200.0,93312.0,93312.0,93312.0
72,73.0,19/08/2022,Sendoz Impex Limited,Prakash,DO20221056,Balaji Traders,Deepak/Prashant,Suliyari,Nepal,28.59,UP72AT2172,3200.0,91488.0,91488.0,91488.0
73,74.0,19/08/2022,Sendoz Impex Limited,Prakash,DO20221056,Balaji Traders,Deepak/Prashant,Suliyari,Nepal,28.95,CG04LE1272,3200.0,92640.0,92640.0,92640.0
74,75.0,19/08/2022,Sendoz Impex Limited,Prakash,DO20221056,Balaji Traders,Deepak/Prashant,Suliyari,Nepal,29.47,CG04ME3060,3200.0,94304.0,94304.0,94304.0

In [9]:
# Calculate profit (revenue - cost)
data['Profit'] = data['Total Revenue'] - data['Total Cost']

In [10]:
data

,S.NO,Date,Company Name,Contact Person No,Delivery Order No,Tranporter Details,Tranport C P,Loading Point,Unloading Point,Coal.Weight,Truck No.,Freight Fair,Freight Chrgs,Total Cost,Total Revenue,Profit
0,1.0,22/06/2022,Sendoz Impex Limited,Prakash,DO20221056,Singh Roadlines,Deepak/Prashant,Suliyari,Nepal,39.79,UP72AT7101,3200.0,127328.0,127328.0,127328.0,0.0
1,2.0,22/06/2022,Sendoz Impex Limited,Prakash,DO20221056,Singh Roadlines,Deepak/Prashant,Suliyari,Nepal,28.92,UP72AT6700,3200.0,92544.0,92544.0,92544.0,0.0
2,3.0,22/06/2022,Sendoz Impex Limited,Prakash,DO20221056,Singh Roadlines,Deepak/Prashant,Suliyari,Nepal,29.43,UP72AT2568,3200.0,94176.0,94176.0,94176.0,0.0
3,4.0,22/06/2022,Sendoz Impex Limited,Prakash,DO20221056,Singh Roadlines,Deepak/Prashant,Suliyari,Nepal,28.98,UP72AT2886,3200.0,92736.0,92736.0,92736.0,0.0
4,5.0,23/06/2022,Sendoz Impex Limited,Prakash,DO20221056,Singh Roadlines,Deepak/Prashant,Suliyari,Nepal,30.17,UP72AT3324,3200.0,96544.0,96544.0,96544.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,71.0,19/08/2022,Sendoz Impex Limited,Prakash,DO20221056,Balaji Traders,Deepak/Prashant,Suliyari,Nepal,29.69,CG15DG7596,3200.0,95008.0,95008.0,95008.0,0.0
71,72.0,19/08/2022,Sendoz Impex Limited,Prakash,DO20221056,Balaji Traders,Deepak/Prashant,Suliyari,Nepal,29.16,CG29AB0150,3200.0,93312.0,93312.0,93312.0,0.0
72,73.0,19/08/2022,Sendoz Impex Limited,Prakash,DO20221056,Balaji Traders,Deepak/Prashant,Suliyari,Nepal,28.59,UP72AT2172,3200.0,91488.0,91488.0,91488.0,0.0
73,74.0,19/08/2022,Sendoz Impex Limited,Prakash,DO20221056,Balaji Traders,Deepak/Prashant,Suliyari,Nepal,28.95,CG04LE1272,3200.0,92640.0,92640.0,92640.0,0.0
74,75.0,19/08/2022,Sendoz Impex Limited,Prakash,DO20221056,Balaji Traders,Deepak/Prashant,Suliyari,Nepal,29.47,CG04ME3060,3200.0,94304.0,94304.0,94304.0,0.0

In [11]:
# Analyze profitability
total_profit = data['Profit'].sum()
print("Total Profit:", total_profit)

Total Profit: 104876.97297297296